spring: 
  application: 
    name: application
  profiles: 
    active: dev

config:
  name: dev


db:
 maxIdleConns: 2
 maxOpenConns: 10
 connMaxLifetime: 3


error:
  msg:
    paymentfailed: "결제 실패"
    orderfailed: "주문 실패"
    test: "1234"
